name: Laravel CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: your_db_name
          POSTGRES_USER: your_db_user
          POSTGRES_PASSWORD: your_db_password

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'

    - name: Install dependencies
      run: composer install

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: your_db_name
        DB_USERNAME: your_db_user
        DB_PASSWORD: your_db_password
      run: php artisan migrate --force

    - name: Run tests
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
        DB_DATABASE: your_db_name
        DB_USERNAME: your_db_user
        DB_PASSWORD: your_db_password
      run: php artisan test
